#############################################################################
# Makefile for building: polypore
# Generated by qmake (2.01a) (Qt 4.7.3) on: Fri Sep 2 18:01:53 2011
# Project:  polypore.pro
# Template: app
# Command: /home/kale/QtSDK/Desktop/Qt/473/gcc/bin/qmake -spec ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++-32 -o Makefile polypore.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -O3 -pipe -fomit-frame-pointer -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -O3 -pipe -fomit-frame-pointer -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++-32 -I. -I../../../QtSDK/Desktop/Qt/473/gcc/include/QtCore -I../../../QtSDK/Desktop/Qt/473/gcc/include/QtGui -I../../../QtSDK/Desktop/Qt/473/gcc/include/QtSvg -I../../../QtSDK/Desktop/Qt/473/gcc/include -I.
LINK          = g++
LFLAGS        = -m32 -Wl,-O1 -Wl,-rpath,/home/kale/QtSDK/Desktop/Qt/473/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/kale/QtSDK/Desktop/Qt/473/gcc/lib -lQtSvg -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/kale/QtSDK/Desktop/Qt/473/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		include/avector3d.cpp \
		include/cycle.cpp \
		include/constants.cpp \
		include/window.cpp \
		include/console.cpp \
		include/field.cpp \
		include/renderer.cpp moc_cycle.cpp \
		moc_window.cpp \
		moc_console.cpp \
		moc_field.cpp \
		moc_renderer.cpp
OBJECTS       = main.o \
		avector3d.o \
		cycle.o \
		constants.o \
		window.o \
		console.o \
		field.o \
		renderer.o \
		moc_cycle.o \
		moc_window.o \
		moc_console.o \
		moc_field.o \
		moc_renderer.o
DIST          = ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/release.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/staticlib.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/static.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf \
		polypore.pro
QMAKE_TARGET  = polypore
DESTDIR       = 
TARGET        = polypore

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: polypore.pro  ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++-32/qmake.conf ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/release.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/staticlib.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/static.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++-32 -o Makefile polypore.pro
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/release.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/staticlib.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/static.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++-32 -o Makefile polypore.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/polypore1.0.0 || $(MKDIR) .tmp/polypore1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/polypore1.0.0/ && $(COPY_FILE) --parents include/avector3d.h include/mtwist.h include/cycle.h include/constants.h include/particle.h include/solver.h include/forces.h include/window.h include/console.h include/field.h include/renderer.h .tmp/polypore1.0.0/ && $(COPY_FILE) --parents main.cpp include/avector3d.cpp include/cycle.cpp include/constants.cpp include/window.cpp include/console.cpp include/field.cpp include/renderer.cpp .tmp/polypore1.0.0/ && (cd `dirname .tmp/polypore1.0.0` && $(TAR) polypore1.0.0.tar polypore1.0.0 && $(COMPRESS) polypore1.0.0.tar) && $(MOVE) `dirname .tmp/polypore1.0.0`/polypore1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/polypore1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cycle.cpp moc_window.cpp moc_console.cpp moc_field.cpp moc_renderer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cycle.cpp moc_window.cpp moc_console.cpp moc_field.cpp moc_renderer.cpp
moc_cycle.cpp: include/avector3d.h \
		include/mtwist.h \
		include/particle.h \
		include/constants.h \
		include/field.h \
		include/solver.h \
		include/forces.h \
		include/cycle.h
	/home/kale/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) include/cycle.h -o moc_cycle.cpp

moc_window.cpp: include/field.h \
		include/avector3d.h \
		include/constants.h \
		include/cycle.h \
		include/mtwist.h \
		include/particle.h \
		include/solver.h \
		include/forces.h \
		include/renderer.h \
		include/window.h
	/home/kale/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) include/window.h -o moc_window.cpp

moc_console.cpp: include/cycle.h \
		include/avector3d.h \
		include/mtwist.h \
		include/particle.h \
		include/constants.h \
		include/field.h \
		include/solver.h \
		include/forces.h \
		include/console.h
	/home/kale/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) include/console.h -o moc_console.cpp

moc_field.cpp: include/avector3d.h \
		include/constants.h \
		include/field.h
	/home/kale/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) include/field.h -o moc_field.cpp

moc_renderer.cpp: include/avector3d.h \
		include/cycle.h \
		include/mtwist.h \
		include/particle.h \
		include/constants.h \
		include/field.h \
		include/solver.h \
		include/forces.h \
		include/renderer.h
	/home/kale/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) include/renderer.h -o moc_renderer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp include/window.h \
		include/field.h \
		include/avector3d.h \
		include/constants.h \
		include/cycle.h \
		include/mtwist.h \
		include/particle.h \
		include/solver.h \
		include/forces.h \
		include/renderer.h \
		include/console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

avector3d.o: include/avector3d.cpp include/avector3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o avector3d.o include/avector3d.cpp

cycle.o: include/cycle.cpp include/cycle.h \
		include/avector3d.h \
		include/mtwist.h \
		include/particle.h \
		include/constants.h \
		include/field.h \
		include/solver.h \
		include/forces.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cycle.o include/cycle.cpp

constants.o: include/constants.cpp include/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o constants.o include/constants.cpp

window.o: include/window.cpp include/window.h \
		include/field.h \
		include/avector3d.h \
		include/constants.h \
		include/cycle.h \
		include/mtwist.h \
		include/particle.h \
		include/solver.h \
		include/forces.h \
		include/renderer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o include/window.cpp

console.o: include/console.cpp include/console.h \
		include/cycle.h \
		include/avector3d.h \
		include/mtwist.h \
		include/particle.h \
		include/constants.h \
		include/field.h \
		include/solver.h \
		include/forces.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o console.o include/console.cpp

field.o: include/field.cpp include/field.h \
		include/avector3d.h \
		include/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o field.o include/field.cpp

renderer.o: include/renderer.cpp include/renderer.h \
		include/avector3d.h \
		include/cycle.h \
		include/mtwist.h \
		include/particle.h \
		include/constants.h \
		include/field.h \
		include/solver.h \
		include/forces.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderer.o include/renderer.cpp

moc_cycle.o: moc_cycle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cycle.o moc_cycle.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

moc_console.o: moc_console.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_console.o moc_console.cpp

moc_field.o: moc_field.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_field.o moc_field.cpp

moc_renderer.o: moc_renderer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_renderer.o moc_renderer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

